"""make uploadedfile room nullable and add session_id

Revision ID: 188056e6ae7f
Revises: 20260223_0018
Create Date: 2026-02-27 11:17:26.575199
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188056e6ae7f'
down_revision: Union[str, Sequence[str], None] = '20260223_0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_llm_call_events_created_at'), table_name='llm_call_events')
    op.drop_index(op.f('idx_llm_call_events_model_alias_created_at'), table_name='llm_call_events')
    op.drop_index(op.f('idx_llm_call_events_session_created_at'), table_name='llm_call_events')
    op.drop_index(op.f('idx_llm_call_events_turn_id'), table_name='llm_call_events')
    op.drop_index(op.f('idx_llm_call_events_user_created_at'), table_name='llm_call_events')
    op.drop_index(op.f('uq_llm_call_events_request_id'), table_name='llm_call_events', postgresql_where='(request_id IS NOT NULL)')
    op.add_column('uploaded_files', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.alter_column('uploaded_files', 'room_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_uploaded_files_session_id'), 'uploaded_files', ['session_id'], unique=False)
    op.create_foreign_key(None, 'uploaded_files', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_index(op.f('ix_uploaded_files_session_id'), table_name='uploaded_files')
    op.alter_column('uploaded_files', 'room_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('uploaded_files', 'session_id')
    op.create_index(op.f('uq_llm_call_events_request_id'), 'llm_call_events', ['request_id'], unique=True, postgresql_where='(request_id IS NOT NULL)')
    op.create_index(op.f('idx_llm_call_events_user_created_at'), 'llm_call_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_llm_call_events_turn_id'), 'llm_call_events', ['turn_id'], unique=False)
    op.create_index(op.f('idx_llm_call_events_session_created_at'), 'llm_call_events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_llm_call_events_model_alias_created_at'), 'llm_call_events', ['model_alias', 'created_at'], unique=False)
    op.create_index(op.f('idx_llm_call_events_created_at'), 'llm_call_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
